:bug: Fix init cannot import name 'escape' from 'jinja2'
It can't run because of newer versions doesn't have older methods
https://www.datasciencelearner.com/importerror-cannot-import-name-escape-from-jinja2-solved/

$ docker-compose up
Creating containerized-aws-sam_sam_1 ... done
Attaching to containerized-aws-sam_sam_1
sam_1  | Traceback (most recent call last):
sam_1  |   File "/usr/local/bin/sam", line 8, in <module>
sam_1  |     sys.exit(cli())
sam_1  |   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
sam_1  |     return self.main(*args, **kwargs)
sam_1  |   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
sam_1  |     rv = self.invoke(ctx)
sam_1  |   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
sam_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sam_1  |   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
sam_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
sam_1  |   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
sam_1  |     return ctx.invoke(self.callback, **ctx.params)
sam_1  |   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
sam_1  |     return callback(*args, **kwargs)
sam_1  |   File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 73, in new_func
sam_1  |     return ctx.invoke(f, obj, *args, **kwargs)
sam_1  |   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
sam_1  |     return callback(*args, **kwargs)
sam_1  |   File "/usr/local/lib/python3.8/dist-packages/samcli/lib/telemetry/metrics.py", line 100, in wrapped
sam_1  |     return func(*args, **kwargs)
sam_1  |   File "/usr/local/lib/python3.8/dist-packages/samcli/commands/local/start_api/cli.py", line 72, in cli
sam_1  |     do_cli(
sam_1  |   File "/usr/local/lib/python3.8/dist-packages/samcli/commands/local/start_api/cli.py", line 118, in do_cli
sam_1  |     from samcli.commands.local.lib.local_api_service import LocalApiService
sam_1  |   File "/usr/local/lib/python3.8/dist-packages/samcli/commands/local/lib/local_api_service.py", line 9, in <module>
sam_1  |     from samcli.local.apigw.local_apigw_service import LocalApigwService
sam_1  |   File "/usr/local/lib/python3.8/dist-packages/samcli/local/apigw/local_apigw_service.py", line 7, in <module>
sam_1  |     from flask import Flask, request
sam_1  |   File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 14, in <module>
sam_1  |     from jinja2 import escape
sam_1  | ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py)
  1 FROM mcr.microsoft.com/playwright:focal
  2
containerized-aws-sam_sam_1 exited with code 1

After the fix, now the SAM server runs without a problem

$ docker-compose up
Recreating containerized-aws-sam_sam_1 ... done
Attaching to containerized-aws-sam_sam_1
sam_1  | Mounting HelloWorldFunction at http://0.0.0.0:3000/hello [GET]
sam_1  | You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
sam_1  | 2022-07-11 07:44:23  * Running on http://0.0.0.0:3000/ (Press CTRL+C to quit)